import {promises as fs} from 'fs';
import {join} from 'path';

/**
 * Delete a file from the local uploads directory when the provided URL
 * references a resource generated by the Upload module.
 */
export async function deleteUploadedFile(
  fileUrl?: string | null,
): Promise<void> {
  if (!fileUrl) return;

  let extractedPath = fileUrl;
  if (fileUrl.startsWith('http')) {
    try {
      extractedPath = new URL(fileUrl).pathname;
    } catch {
      return;
    }
  }

  const match = extractedPath.match(/uploads\/(.+)$/);
  if (!match) return;

  const relativeFile = match[1];
  if (!relativeFile || relativeFile.includes('..')) return;

  const absolutePath = join(process.cwd(), 'uploads', relativeFile);
  try {
    await fs.unlink(absolutePath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn(`Unable to delete file ${absolutePath}`, error);
    }
  }
}
